---
- name: Install packages
  sudo: yes
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
    # Utilities
    - unzip

    # Database
    - mysql-server
    - python-mysqldb # required for ansible mysql integration

    # PHP
    - php5
    - php5-cli
    - php5-mysql
    - php5-curl
    - php5-gd
    - php5-sqlite
    - php5-xmlrpc
    - php5-imagick
    - php5-xcache
    - php5-mysql

    # Apache
    - apache2
    - libapache2-mod-php5

- name: Start Mysql Service
  sudo: yes
  service: name=mysql state=started enabled=true

- name: Ensure database is present
  sudo: yes
  mysql_db: name={{db_name}} state=present

- name: Ensure database user is present
  sudo: yes
  mysql_user: name={{db_user}} password={{db_password}} priv={{db_name}}.*:ALL host={{item}} state=present
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost


- name: download WordPress
  get_url: url=https://wordpress.org/wordpress-{{wordpress_version}}.tar.gz dest=/tmp/

- name: unzip WordPress
  sudo: yes
  unarchive: src=/tmp/wordpress-{{wordpress_version}}.tar.gz dest=/var/www/ copy=no creates=/var/www/wordpress/readme.html owner=vagrant group=vagrant

- name: Fetch random salts for Wordpress config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"

- name: delete default WordPress themes
  file: path=/var/www/wordpress/wp-content state="absent"
- name: link WordPress files
  file: path=/var/www/wordpress/wp-content state=link src="/var/agigen/wp-content"
- name: copy WordPress config
  template: dest=/var/www/wordpress/wp-config.php src=wp-config.php
- name: copy htaccess file
  template: dest=/var/www/wordpress/.htaccess src=.htaccess

# - name: link WordPress files
#   sudo: yes
#   file: path=/var/www/wordpress state=link src=/vagrant/wordpress

- name: Enable modules
  sudo: yes
  command: a2enmod {{item}}
  with_items:
    - expires
    - headers
    - rewrite
  notify: restart apache

- name: copy virtual host setup over
  sudo: yes
  template: src=vhost.conf dest=/etc/apache2/sites-available/vhost.conf

- name: activate virtual host
  sudo: yes
  command: a2ensite vhost
  notify: restart apache

- name: deactivate default vhost
  sudo: yes
  command: a2dissite 000-default
  notify: restart apache

- name: Start Apache2 Service
  sudo: yes
  service: name=apache2 state=started enabled=true
